name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: godot-jam-template

jobs:
  configure-version:
    name: Configure Version
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    outputs:
      gitversion: ${{ steps.gitversion.outputs.gitversion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          filter: "tree:0"
      - name: Get Git Version
        id: gitversion
        run: |
          git config --global --add safe.directory $(pwd)
          echo "gitversion=$(git describe --always --long)" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    needs: configure-version
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot --headless --verbose --export-release "Windows Desktop" build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows-${{ needs.configure-version.outputs.gitversion }}
          path: build/windows

  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    needs: configure-version
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          godot --headless --verbose --export-release "Linux/X11" build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux-${{ needs.configure-version.outputs.gitversion }}
          path: build/linux

  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    needs: configure-version
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot --headless --verbose --export-release "Web" build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web-${{ needs.configure-version.outputs.gitversion }}
          path: build/web
