name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: godot-jam-template

jobs:
  configure-version:
    name: Configure Version
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    outputs:
      gitversion: ${{ steps.gitversion.outputs.gitversion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          filter: "tree:0"
      - name: Get Git Version
        id: gitversion
        run: |
          git config --global --add safe.directory $(pwd)
          echo "gitversion=$(git describe --always --long)" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  export-matrix:
    strategy:
      matrix:
        os: [windows, linux, web]
        include:
          - os: windows
            name: Windows Desktop
          - os: linux
            name: Linux/X11
          - os: web
            name: Web
    needs: configure-version
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -v -p build/${{ matrix.os }}
          godot --headless --verbose --export-release "${{ matrix.name }}"
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-${{ needs.configure-version.outputs.gitversion }}
          path: build/${{ matrix.os }}
          
    
